### PR TITLE
[FIX] account_move_change_currency: New attribute in message_post method

### PR DESCRIPTION
**Pull request by mem-adhoc**
Ticket: 74025

### CODE REVIEW

**Comment by mem-adhoc** [comment]
Hello @Danisan, how are you doing?
This Fix is ​​because there is now a new argument that is passed to the message_post method.
body_is_html is False by default, so we have to inform it when we pass it an HTML.

**Comment by mem-adhoc** [comment]
@Danisan Hi Daniel, could you see this PR?

**Comment by mem-adhoc** [comment]
@Danisan Hi Daniel, could you see this PR?

**Comment by Danisan** [comment]
> @Danisan Hi Daniel, could you see this PR?

@mem-adhoc thanks and sorry for the delay.

**Pull request merged**
